<?php
/**
*@file
*Имитация звукового сигнала.
*/
function beep_beep(){
	watchdog('beep','Beep!');
}

function beep_action_info(){
	return array(
	'beep_beep_action' => array(
		'type' => 'system',
		'label' => t('Beep annoyingly'), //противно гудит
		'configurable' => FALSE,
		'triggers' => array('any'),
		),
	);
}
/**
* Действие Drupal - имитация гудка
*/
function beep_beep_action(){
	beep_beep();
}








