<?php
/**
*@file
* Использование форм API.
*/
/**
* Реализация hook_menu()
*/
function formexample_menu(){
	$items['formexample'] = array(
		'title' => t('View the sample form'),
		'page callback' => 'drupal_get_form',
		'page arguments' => array('formexample_nameform'),
		'access callback' => TRUE,
		'type' => MENU_NORMAL_ITEM,
	);
	return $items;
}
/**
* Определение формы.
*/
function formexample_nameform(){
	$form['user_name'] = array(
		'#title' => t('Your Name'),
		'#type' => 'textfield',
		'#description' => t('Please enter your name.'),
	);
	$form['submit'] = array(
		'#type' => 'submit',
		'#value' => t('Submit'),
	);
	$form['#prefix'] = '<div class="my-form-clsassik">';
	$form['#sufix'] = '</div>';
	return $form;
}
/**
* Проверка достоверности формы.
*/
function formexample_nameform_validate($form, &$form_state){
	if($form_state['values']['user_name'] == 'King Kong'){
		// Уведомить что данное поле не прошло проверку.
		form_set_error('user_name',t('King Kong is not allowed to use this form.'));
	}
}
/**
* Обработка отправки формы после проверки достоверости
*/
function formexample_nameform_submit($form, &$form_state){
	$name = $form_state['values']['user_name'];
	drupal_set_message(t('Thanks for filling out the form, %name', array('%name' => $name)));
}



